---
title: "FishAssignment"
author: "Celine Mol, Paige Fitzgibbon"
date: "6/2/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(devtools)
library(roxygen2)
library(testthat)
library(Homework3)
load_all() # This will load all the packages
```

# Fish Assignment

## Part 1. Fish Market Function

### Part 1.a Generate example data

```{r}
# ----- Fish Prices ----- #

fish = c("Cod", "Salmon", "Steelhead", "Tuna", "Shark", "Sole")
price = c(34.89, 26.66, 15.41, 13.84, 58.66, 63.96)
fish_price = data.frame(fish, price)
fish_price$fish = as.character(fish_price$fish)

# ----- Fish Catches by Location ----- # 

locs = c("location1", "location2", "location3")
fish_catches = matrix(nrow = length(fish), ncol = length(locs), 
                      dimnames = list(fish, locs)) 

for ( i in 1: length(fish)) {
  for (j in 1:length(locs)) {
      fish_catches[i,j] =  sample(1:100, 1)
  }
}

```

### Part 1.b Export example data to csv file for package DATA

```{r}
fish_catches = as.data.frame(fish_catches)
write.csv(fish_catches, file = 'fishmarketdata', row.names = TRUE)
```

### Part 1.c Run the function

```{r}
fishmarketdata = fish_catches
use_data(fishmarketdata, pkg = ".", overwrite=TRUE)
# issue - can't find package 'Homework3' - help?
data(fishmarketdata)
help(fishmarketdata)

fisheries(fish_price, fishmarketdata, showplot=FALSE)

fisheries(fish_price, fishmarketdata, showplot=TRUE)
```

## Part 2. Fish Growth Rate Function
*Instructions:*
**Show an example of using your growth rate function with parameters from Experiment A from Table 2**

```{r}
help(fishgrowth)

fishgrowth(a = -0.4970, b = 0.1656, c = 0.08588, d = -0.004266, T = 14.3)


```





